# Source: jxboot-helmfile-resources/templates/jx-gcpods-crb-ns.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gcpods-cluster-scoped-ns-listing
  annotations:
    meta.helm.sh/release-name: 'jxboot-helmfile-resources'
  labels:
    gitops.jenkins-x.io/pipeline: 'cluster'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gcpods-cluster-scoped-ns-listing
subjects:
  - kind: ServiceAccount
    name: jx-gcpods
    namespace: jx
