# Source: lighthouse/templates/gc-jobs-clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lighthouse-gc-jobs-cluster-scoped
  annotations:
    meta.helm.sh/release-name: 'lighthouse'
  labels:
    gitops.jenkins-x.io/pipeline: 'cluster'
rules:
  - apiGroups:
      - lighthouse.jenkins.io
    resources:
      - lighthousejobs
    verbs:
      - delete
      - list
      - get
