# Source: lighthouse/templates/webhooks-clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lighthouse-webhooks-cluster-scoped
  annotations:
    meta.helm.sh/release-name: 'lighthouse'
  labels:
    gitops.jenkins-x.io/pipeline: 'cluster'
rules:
  - apiGroups:
      - lighthouse.jenkins.io
    resources:
      - lighthousejobs
    verbs:
      - create
      - delete
      - list
      - update
      - get
      - watch
      - patch
  - apiGroups:
      - lighthouse.jenkins.io
    resources:
      - lighthousejobs/status
    verbs:
      - create
      - delete
      - list
      - update
      - get
      - watch
      - patch
