# Source: lighthouse/templates/gc-jobs-rb.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lighthouse-gc-jobs-global-lh
  annotations:
    meta.helm.sh/release-name: 'lighthouse'
  labels:
    gitops.jenkins-x.io/pipeline: 'cluster'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lighthouse-gc-jobs-global-lh
subjects:
  - kind: ServiceAccount
    name: lighthouse-gc-jobs
    namespace: jx
