# Source: lighthouse/templates/webhooks-role.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lighthouse-webhooks
  annotations:
    meta.helm.sh/release-name: 'lighthouse'
  labels:
    gitops.jenkins-x.io/pipeline: 'cluster'
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - configmaps
      - secrets
    verbs:
      - get
      - update
      - create
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - lighthouse.jenkins.io
    resources:
      - lighthousejobs
    verbs:
      - create
      - delete
      - list
      - update
      - get
      - watch
      - patch
  - apiGroups:
      - lighthouse.jenkins.io
    resources:
      - lighthousejobs/status
    verbs:
      - create
      - delete
      - list
      - update
      - get
      - watch
      - patch
  - apiGroups:
      - lighthouse.jenkins.io
    resources:
      - lighthousepipelinesecuritypolicies
    verbs:
      - list
      - get
