# Source: lighthouse/templates/tekton-controller-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighthouse-tekton-controller
  labels:
    chart: "lighthouse-0.4.0"
    app: lighthouse-tekton-controller
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'lighthouse'
    wave.pusher.com/update-on-config-change: 'true'
  namespace: jx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lighthouse-tekton-controller
  template:
    metadata:
      labels:
        app: lighthouse-tekton-controller
      annotations: {jenkins-x.io/hash: 'bfe75699df8e8cf24452c09f7adf9449320f6ded92058cb2d470e899eae89f5e'}
    spec:
      serviceAccountName: lighthouse-tekton-controller
      containers:
        - name: lighthouse-tekton-controller
          image: quay.io/keskad/jx3-test-tekton:latest
          imagePullPolicy: IfNotPresent
          args:
            - --namespace=jx
            - --dashboard-url=http://dashboard.jx.k3s-dev.keskad.pl
            - --dashboard-template=namespaces/{{ .Namespace }}/pipelineruns/{{ .PipelineRun }}
          ports:
            - name: metrics
              containerPort: 8080
          env:
            - name: "LOGRUS_FORMAT"
              value: "json"
            - name: LOGRUS_SERVICE
              value: "lighthouse"
            - name: LOGRUS_SERVICE_VERSION
              value: "0.4.0"
            - name: LOGRUS_STACK_SKIP
              value: ""
            - name: DEFAULT_PIPELINE_RUN_SERVICE_ACCOUNT
              value: "tekton-bot"
            - name: DEFAULT_PIPELINE_RUN_TIMEOUT
              value: "2h0m0s"
            - name: FILE_BROWSER
              value: "git"
            - name: JX_DEFAULT_IMAGE
              value: "ghcr.io/jenkins-x/builder-maven:2.1.149-768"
            - name: LIGHTHOUSE_DASHBOARD_TEMPLATE
              value: "namespaces/{{ .Namespace }}/pipelineruns/{{ .PipelineRun }}"
            - name: LIGHTHOUSE_VERSIONSTREAM_JENKINS_X_JX3_PIPELINE_CATALOG
              value: "8f23a5446f6f026f5395d53298638faec245136e"
          envFrom:
            - secretRef:
                name: jx-boot-job-env-vars
                optional: true
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 80m
              memory: 128Mi
      terminationGracePeriodSeconds: 180
      nodeSelector: {}
      affinity: {}
      tolerations: []
