# Source: lighthouse/templates/keeper-role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lighthouse-keeper
  annotations:
    meta.helm.sh/release-name: 'lighthouse'
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - configmaps
    verbs:
      - get
      - list
      - watch
